---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    # - name: Wait for systemd to complete initialization. # noqa 303
    #   command: systemctl is-system-running
    #   register: systemctl_status
    #   until: >
    #     'running' in systemctl_status.stdout or
    #     'degraded' in systemctl_status.stdout
    #   retries: 30
    #   delay: 5
    #   # when: ansible_service_mgr == 'systemd'
    #   changed_when: false
    #   failed_when: systemctl_status.rc > 1

  tasks:
    - apt:
        name: curl
        state: present

    - name: "Include Syncthing Role"
      include_role:
        name: "ansible-role-syncthing"
