---
- name: Verify
  hosts: all

  tasks:
    - name: Collect package facts.
      package_facts:
        manager: "auto"

    - name: Verify Syncthing is installed.
      assert:
        that:
          - "'syncthing' in ansible_facts.packages"
        success_msg: "Syncthing is installed."
        fail_msg: "Syncthing is not installed."
